import { create } from "zustand";
import {
  bindSelectedFile,
  cancelUpload,
  connect,
  discardSelectedFile,
  downloadFile,
  loadDetectedProfile,
  loadIdentity,
  receiveCapability,
  selectFile,
  send,
  saveDisplayName,
  uploadSelectedFile,
} from "../browser/ffi";
import type { FileSelection } from "../browser/types";
import * as core from "../core.gleam";
import * as reconnect from "../reconnect.gleam";
import {
  addIncomingTransfer,
  addOutgoingTransfer,
  addTextMessage,
  addTextMessages,
  addTransferHistory,
  bindOutgoingTransfer,
  clearPendingDraft,
  conversationPeerId,
  interruptedTransferIds,
  isRelayFileSizeAllowed,
  isPeerOnline,
  localFile,
  maxRelayFileSizeBytes,
  markConnectionLost,
  markTransferProgress,
  markTransferReady,
  markTransferStatus,
  otherPeers,
  rememberMissingPeers,
  rememberPeer,
  rememberPeers,
  removePeer,
  setDraft,
  transferHistoryPeers,
  upsertPeer,
} from "./domain";
import { formatBytes } from "./format";
import type {
  ConnectionStatus,
  DeviceProfile,
  FileOffer,
  LocalFile,
  Peer,
  PendingDraftClear,
  ServerEvent,
  TextMessage,
  TransferItem,
} from "./types";

interface AppState {
  deviceId: string;
  displayName: string;
  displayNameAutogenerated: boolean;
  deviceProfile: DeviceProfile;
  status: ConnectionStatus;
  connectionGeneration: number;
  reconnectAttempt: number;
  initialized: boolean;
  peers: Peer[];
  knownPeers: Record<string, Peer>;
  selectedPeerId: string | null;
  messageDrafts: Record<string, string>;
  messagesByPeer: Record<string, TextMessage[]>;
  unreadByPeer: Record<string, number>;
  transfers: TransferItem[];
  localFiles: Record<string, LocalFile>;
  pendingFilePeerId: string | null;
  chatNotice: string | null;
  pendingDraftClear: PendingDraftClear | null;
  log: string[];
  logOpen: boolean;
  setLogOpen: (open: boolean) => void;
  transfersOpen: boolean;
  setTransfersOpen: (open: boolean) => void;
  topologyOpen: boolean;
  setTopologyOpen: (open: boolean) => void;
  clearNotice: () => void;
  initialize: () => void;
  setDisplayName: (name: string) => void;
  connectNow: () => void;
  selectPeer: (peerId: string) => void;
  deselectPeer: () => void;
  setSelectedDraft: (body: string) => void;
  sendMessage: () => void;
  selectFileForCurrentPeer: () => void;
  sendFileOffer: (selection: FileSelection) => void;
  acceptFile: (transferId: string) => void;
  declineFile: (transferId: string) => void;
  cancelFile: (transferId: string) => void;
  downloadTransfer: (transferId: string) => void;
  clearLog: () => void;
  activePeer: () => Peer | null;
  selectedMessages: () => TextMessage[];
}

const defaultDisplayName = "Glim Peer";

export const useAppStore = create<AppState>()((set, get) => ({
  deviceId: "",
  displayName: defaultDisplayName,
  displayNameAutogenerated: true,
  deviceProfile: {
    kind: "unknown",
    os: "unknown",
    browser: "unknown",
    input: "unknown",
    model: null,
    confidence: "low",
    reasons: ["classification pending"],
  },
  status: "disconnected",
  connectionGeneration: 0,
  reconnectAttempt: 0,
  initialized: false,
  peers: [],
  knownPeers: {},
  selectedPeerId: null,
  messageDrafts: {},
  messagesByPeer: {},
  unreadByPeer: {},
  transfers: [],
  localFiles: {},
  pendingFilePeerId: null,
  chatNotice: null,
  pendingDraftClear: null,
  log: [],
  logOpen: false,
  setLogOpen(open) {
    set({ logOpen: open });
  },
  transfersOpen: false,
  setTransfersOpen(open) {
    set({ transfersOpen: open });
  },
  topologyOpen: false,
  setTopologyOpen(open) {
    set({ topologyOpen: open });
  },
  clearNotice() {
    set({ chatNotice: null });
  },

  initialize() {
    if (get().initialized) {
      return;
    }

    const identity = loadIdentity();
    set({
      initialized: true,
      deviceId: identity.device_id,
      displayName: identity.display_name,
      displayNameAutogenerated: identity.display_name_is_default,
      deviceProfile: identity.device_profile,
    });
    get().connectNow();
    void refreshDeviceProfile();
  },

  setDisplayName(name) {
    const displayName = core.normalize_display_name(name);
    saveDisplayName(displayName);
    set({ displayName, displayNameAutogenerated: false });

    const state = get();
    if (state.status === "connected") {
      send(core.encode_peer_update_display_name(displayName), sendFailed);
      return;
    }

    get().connectNow();
  },

  connectNow() {
    connectWithAttempt(get, set, 0, "connecting");
  },

  selectPeer(peerId) {
    set((state) => {
      const nextUnread = { ...state.unreadByPeer };
      delete nextUnread[peerId];
      return {
        selectedPeerId: peerId,
        unreadByPeer: nextUnread,
        chatNotice: null,
      };
    });
  },

  deselectPeer() {
    set({ selectedPeerId: null });
  },

  setSelectedDraft(body) {
    const selectedPeerId = get().selectedPeerId;
    if (!selectedPeerId) {
      return;
    }

    set((state) => ({
      messageDrafts: setDraft(state.messageDrafts, selectedPeerId, body),
    }));
  },

  sendMessage() {
    const state = get();
    const request = sendMessageRequest(state);
    if (!request.ok) {
      set({ chatNotice: request.notice });
      return;
    }

    set((current) => ({
      messageDrafts: setDraft(current.messageDrafts, request.peerId, request.body),
      chatNotice: null,
      pendingDraftClear: { to: request.peerId, body: request.body },
    }));
    send(core.encode_text_send(request.peerId, request.body), () => {
      set({
        status: "connection_error",
        chatNotice: "Message could not be sent.",
      });
    });
  },

  selectFileForCurrentPeer() {
    const state = get();
    const target = sendFileTarget(state);
    if (!target.ok) {
      set({ chatNotice: target.notice });
      return;
    }

    set({ pendingFilePeerId: target.peerId });
    selectFile(get().sendFileOffer, () => {
      set({ pendingFilePeerId: null, chatNotice: "File selection was cancelled." });
    });
  },

  sendFileOffer(selection) {
    const state = get();
    const peerId = state.pendingFilePeerId;
    if (!peerId) {
      set({ chatNotice: "Select an online peer before sharing a file." });
      return;
    }

    if (!isRelayFileSizeAllowed(selection.size)) {
      discardSelectedFile(selection.client_offer_id);
      set({
        pendingFilePeerId: null,
        chatNotice: `Files must be ${formatBytes(maxRelayFileSizeBytes)} or smaller.`,
      });
      return;
    }

    const peerName = peerDisplayName(state, peerId);
    set((current) => ({
      pendingFilePeerId: null,
      chatNotice: null,
      transfers: addOutgoingTransfer(current.transfers, peerId, peerName, selection),
      localFiles: {
        ...current.localFiles,
        [selection.client_offer_id]: localFile(selection),
      },
    }));
    send(
      core.encode_file_offer(
        peerId,
        selection.client_offer_id,
        selection.name,
        selection.size,
        selection.mime_type,
      ),
      sendFailed,
    );
  },


  acceptFile(transferId) {
    const item = get().transfers.find((transfer) => transfer.transfer_id === transferId);
    if (!item) {
      set({ chatNotice: "That file transfer is no longer available." });
      return;
    }

    if (item.status !== "offered") {
      return;
    }

    set((state) => ({
      transfers: markTransferStatus(
        state.transfers,
        transferId,
        "transferring",
        "Waiting for upload",
      ),
    }));
    send(core.encode_file_accept(transferId), sendFailed);
  },

  declineFile(transferId) {
    set((state) => ({
      transfers: markTransferStatus(state.transfers, transferId, "declined", "Declined"),
    }));
    send(core.encode_file_decline(transferId), sendFailed);
  },

  cancelFile(transferId) {
    set((state) => {
      const nextLocalFiles = { ...state.localFiles };
      delete nextLocalFiles[transferId];
      return {
        localFiles: nextLocalFiles,
        transfers: markTransferStatus(state.transfers, transferId, "cancelled", "Cancelled"),
      };
    });
    send(core.encode_file_cancel(transferId), sendFailed);
    cancelUpload(transferId);
  },

  downloadTransfer(transferId) {
    const transfer = get().transfers.find((item) => item.transfer_id === transferId);
    if (!transfer?.download_url) {
      set({ chatNotice: "This transfer is not ready to download." });
      return;
    }

    downloadFile(transfer.download_url);
  },


  clearLog() {
    set({ log: [] });
  },

  activePeer() {
    const state = get();
    return state.selectedPeerId ? state.knownPeers[state.selectedPeerId] ?? null : null;
  },

  selectedMessages() {
    const state = get();
    return state.selectedPeerId ? state.messagesByPeer[state.selectedPeerId] ?? [] : [];
  },
}));

function connectWithAttempt(
  get: () => AppState,
  set: (partial: Partial<AppState> | ((state: AppState) => Partial<AppState>)) => void,
  attempt: number,
  status: ConnectionStatus,
): void {
  const state = get();
  const displayName = core.normalize_display_name(state.displayName);
  const generation = state.connectionGeneration + 1;
  const helloJson = core.encode_peer_hello(
    state.deviceId,
    displayName,
    state.deviceProfile.kind,
  );

  set({
    displayName,
    status,
    connectionGeneration: generation,
    reconnectAttempt: attempt,
  });

  connect(
    displayName,
    helloJson,
    () => socketOpened(generation),
    () => connectionLost(generation),
    () => connectionLost(generation),
    (raw) => socketReceived(generation, raw),
    fileReceiveFailed,
  );
}

function socketOpened(generation: number): void {
  const state = useAppStore.getState();
  if (generation !== state.connectionGeneration) {
    return;
  }

  useAppStore.setState({
    status: "connected",
    reconnectAttempt: 0,
    chatNotice: null,
  });
  sendCurrentPeerMetadata();
}

function connectionLost(generation: number): void {
  const state = useAppStore.getState();
  if (generation !== state.connectionGeneration || state.status === "reconnecting") {
    return;
  }

  const attempt = state.reconnectAttempt + 1;
  const delay = reconnect.retry_delay_ms(attempt);
  for (const transferId of interruptedTransferIds(state.transfers)) {
    cancelUpload(transferId);
  }

  useAppStore.setState({
    status: "reconnecting",
    reconnectAttempt: attempt,
    peers: [],
    knownPeers: {},
    transfers: markConnectionLost(state.transfers),
    localFiles: {},
    chatNotice: "Mesh disconnected. Reconnecting...",
  });

  window.setTimeout(() => {
    const next = useAppStore.getState();
    if (generation === next.connectionGeneration && attempt === next.reconnectAttempt) {
      connectWithAttempt(useAppStore.getState, useAppStore.setState, attempt, "reconnecting");
    }
  }, delay);
}

function socketReceived(generation: number, raw: string): void {
  const state = useAppStore.getState();
  if (generation !== state.connectionGeneration) {
    return;
  }

  handleServerEvent(raw);
}

function handleServerEvent(raw: string): void {
  const event = JSON.parse(core.server_event_json(raw)) as ServerEvent;
  useAppStore.setState((state) => ({ log: [...state.log, raw] }));

  switch (event.kind) {
    case "peer_list":
      useAppStore.setState((state) => ({
        peers: otherPeers(event.peers, state.deviceId),
        knownPeers: rememberPeers(
          state.knownPeers,
          otherPeers(event.peers, state.deviceId),
        ),
      }));
      break;
    case "peer_joined":
      if (event.peer.id === useAppStore.getState().deviceId) {
        break;
      }
      useAppStore.setState((state) => ({
        peers: upsertPeer(state.peers, event.peer),
        knownPeers: rememberPeer(state.knownPeers, event.peer),
      }));
      break;
    case "peer_updated":
      if (event.peer.id === useAppStore.getState().deviceId) {
        break;
      }
      useAppStore.setState((state) => ({
        peers: upsertPeer(state.peers, event.peer),
        knownPeers: rememberPeer(state.knownPeers, event.peer),
      }));
      break;
    case "peer_left":
      useAppStore.setState((state) => ({
        peers: removePeer(state.peers, event.device_id),
      }));
      break;
    case "text_message":
      applyTextMessage(event.message);
      break;
    case "message_history":
      useAppStore.setState((state) => ({
        messagesByPeer: addTextMessages(
          state.messagesByPeer,
          state.deviceId,
          event.messages,
        ),
      }));
      break;
    case "transfer_history":
      useAppStore.setState((state) => ({
        knownPeers: rememberMissingPeers(
          state.knownPeers,
          transferHistoryPeers(state.deviceId, event.history),
        ),
        transfers: addTransferHistory(
          state.transfers,
          state.deviceId,
          event.history,
        ),
      }));
      break;
    case "file_offered":
      applyFileOffered(event.offer);
      break;
    case "transfer_accepted":
      applyTransferAccepted(event.transfer_id, event.upload_url);
      break;
    case "file_declined":
      useAppStore.setState((state) => ({
        transfers: markTransferStatus(state.transfers, event.transfer_id, "declined", "Declined"),
      }));
      break;
    case "file_cancelled":
      useAppStore.setState((state) => {
        const nextLocalFiles = { ...state.localFiles };
        delete nextLocalFiles[event.transfer_id];

        return {
          localFiles: nextLocalFiles,
          transfers: markTransferStatus(
            state.transfers,
            event.transfer_id,
            "cancelled",
            event.reason,
          ),
        };
      });
      cancelUpload(event.transfer_id);
      break;
    case "transfer_progress":
      useAppStore.setState((state) => ({
        transfers: markTransferProgress(state.transfers, event.progress),
      }));
      break;
    case "transfer_ready":
      useAppStore.setState((state) => ({
        transfers: markTransferReady(state.transfers, event.transfer_id, event.download_url),
      }));
      break;
    case "transfer_done":
      useAppStore.setState((state) => {
        const nextLocalFiles = { ...state.localFiles };
        delete nextLocalFiles[event.transfer_id];
        return {
          localFiles: nextLocalFiles,
          transfers: markTransferStatus(
            state.transfers,
            event.transfer_id,
            "completed",
            "Download started",
          ),
        };
      });
      break;
    case "transfer_failed":
      useAppStore.setState((state) => ({
        transfers: markTransferStatus(state.transfers, event.transfer_id, "failed", event.reason),
      }));
      cancelUpload(event.transfer_id);
      break;
    case "error":
      useAppStore.setState((state) => ({
        chatNotice:
          core.server_error_notice(event.code, event.message, state.chatNotice ?? "") ||
          state.chatNotice,
      }));
      break;
    case "unknown":
      break;
    case "invalid":
      useAppStore.setState((state) => ({ log: [...state.log, event.message] }));
      break;
  }
}

function applyTextMessage(message: TextMessage): void {
  useAppStore.setState((state) => {
    const peerId = conversationPeerId(state.deviceId, message);
    const messagesByPeer = addTextMessage(state.messagesByPeer, state.deviceId, message);
    const unreadByPeer =
      message.from !== state.deviceId && state.selectedPeerId !== peerId
        ? {
            ...state.unreadByPeer,
            [peerId]: (state.unreadByPeer[peerId] ?? 0) + 1,
          }
        : state.unreadByPeer;
    const draft = clearPendingDraft(state.pendingDraftClear, state.messageDrafts, message);

    return {
      messagesByPeer,
      unreadByPeer,
      messageDrafts: draft.messageDrafts,
      pendingDraftClear: draft.pendingDraftClear,
      chatNotice: state.selectedPeerId === peerId ? null : state.chatNotice,
    };
  });
}

function applyFileOffered(offer: FileOffer): void {
  const state = useAppStore.getState();
  if (offer.from === state.deviceId && offer.client_offer_id) {
    const clientOfferId = offer.client_offer_id;
    bindSelectedFile(clientOfferId, offer.transfer_id);
    useAppStore.setState((current) => {
      const nextLocalFiles = { ...current.localFiles };
      const local = nextLocalFiles[clientOfferId];
      delete nextLocalFiles[clientOfferId];
      if (local) {
        nextLocalFiles[offer.transfer_id] = local;
      }
      return {
        localFiles: nextLocalFiles,
        transfers: bindOutgoingTransfer(current.transfers, clientOfferId, offer),
      };
    });
    return;
  }

  useAppStore.setState((current) => ({
    transfers: addIncomingTransfer(
      current.transfers,
      offer,
      peerDisplayName(current, offer.from),
      receiveCapability(),
    ),
  }));
}

function applyTransferAccepted(transferId: string, uploadUrl: string): void {
  const state = useAppStore.getState();
  if (!state.localFiles[transferId]) {
    useAppStore.setState((current) => ({
      transfers: markTransferStatus(current.transfers, transferId, "transferring", "Waiting for upload"),
    }));
    return;
  }

  useAppStore.setState((current) => ({
    transfers: markTransferStatus(current.transfers, transferId, "transferring", "Uploading"),
  }));
  uploadSelectedFile(
    transferId,
    uploadUrl,
    (bytes, total) => {
      useAppStore.setState((current) => ({
        transfers: markTransferProgress(current.transfers, {
          transfer_id: transferId,
          phase: "uploading",
          bytes,
          total,
        }),
      }));
    },
    () => {
      useAppStore.setState((current) => ({
        transfers: markTransferStatus(current.transfers, transferId, "transferring", "Processing upload"),
      }));
    },
    (reason) => {
      useAppStore.setState((current) => ({
        transfers: markTransferStatus(current.transfers, transferId, "failed", reason),
      }));
      send(core.encode_file_cancel(transferId), sendFailed);
    },
  );
}

async function refreshDeviceProfile(): Promise<void> {
  const detected = await loadDetectedProfile();
  const state = useAppStore.getState();
  const nextDisplayName = state.displayNameAutogenerated
    ? detected.generated_display_name
    : state.displayName;

  if (state.displayNameAutogenerated) {
    saveDisplayName(nextDisplayName);
  }

  useAppStore.setState({
    deviceProfile: detected.profile,
    displayName: nextDisplayName,
  });

  if (useAppStore.getState().status === "connected") {
    sendCurrentPeerMetadata();
  }
}

function sendCurrentPeerMetadata(): void {
  const state = useAppStore.getState();
  const model = state.deviceProfile.model ?? "";

  send(
    core.encode_peer_update_metadata(
      state.deviceProfile.kind,
      state.deviceProfile.os,
      state.deviceProfile.browser,
      model,
    ),
    sendFailed,
  );

  if (state.displayNameAutogenerated) {
    send(core.encode_peer_update_display_name(state.displayName), sendFailed);
  }
}

function fileReceiveFailed(transferId: string, reason: string): void {
  useAppStore.setState((state) => ({
    transfers: transferId
      ? markTransferStatus(state.transfers, transferId, "failed", reason)
      : state.transfers,
  }));

  if (transferId) {
    send(core.encode_file_cancel(transferId), sendFailed);
  }
}

function sendMessageRequest(state: AppState):
  | { ok: true; peerId: string; body: string }
  | { ok: false; notice: string } {
  if (state.status !== "connected") {
    return {
      ok: false,
      notice:
        state.status === "connecting"
          ? "Waiting for mesh connection."
          : state.status === "reconnecting"
            ? "Waiting for mesh reconnection."
            : "Connect before sending messages.",
    };
  }
  if (!state.selectedPeerId) {
    return { ok: false, notice: "Select a peer before sending." };
  }
  if (!isPeerOnline(state.peers, state.selectedPeerId)) {
    return { ok: false, notice: "That peer is offline." };
  }
  const body = (state.messageDrafts[state.selectedPeerId] ?? "").trim();
  if (!body) {
    return { ok: false, notice: "Type a message before sending." };
  }
  return { ok: true, peerId: state.selectedPeerId, body };
}

function sendFileTarget(state: AppState):
  | { ok: true; peerId: string }
  | { ok: false; notice: string } {
  if (state.status !== "connected") {
    return { ok: false, notice: "Connect before sharing files." };
  }
  if (!state.selectedPeerId) {
    return { ok: false, notice: "Select a peer before sending." };
  }
  if (!isPeerOnline(state.peers, state.selectedPeerId)) {
    return { ok: false, notice: "That peer is offline." };
  }
  return { ok: true, peerId: state.selectedPeerId };
}

function peerDisplayName(state: AppState, peerId: string): string {
  return state.knownPeers[peerId]?.display_name ?? peerId;
}

function sendFailed(): void {
  useAppStore.setState({
    status: "connection_error",
    chatNotice: "Message could not be sent.",
  });
}
